### ISSUE TITLE
Update the How to contribute section in the README

### ISSUE THREAD

**Issue by jdwilkin4** [DBenMoshe/contrast-ratio-repo#108]
We need to make some updates in this section so new developers will know how to properly contribute to this repo.

Please add this text before the list of steps in the How to contribute section

**Please note**: If you are not marked as a contributor for this project, then you will need to follow the first two steps. If you are marked as a contributor, then you can clone the repo `git clone https://github.com/DBenMoshe/contrast-ratio-repo.git` and then follow the rest of the steps in order.

**Comment by thetalesofj** [comment]
Hi, I'll complete this issue :)
