### ISSUE TITLE
Implement hex conversion and display result 

### ISSUE THREAD

**Issue by jdwilkin4** [DBenMoshe/contrast-ratio-repo#24]
Right now, we will just focus on when the user inputs two hex values for the background and foreground.
We'll worry about the other conversions later.

As a user I should be able to input two hex values and the contrast ratio will automatically display.

<img width="682" alt="Screen Shot 2022-08-07 at 5 30 39 PM" src="https://user-images.githubusercontent.com/67210629/183317558-d1be3d8c-8799-45f9-87fc-fad9a071f26e.png">

We want to mimic the same basic behavior here: https://webaim.org/resources/contrastchecker/
Don't worry about the colors changing and all of those extra features for now. Just focus on the functionality.

**Comment by jdwilkin4** [comment]
> I am wondering, how I have vanilla JS FCC certification and don't know stuff like that. 

The new course will teach DOM manipulation. 
There will be 15 practice projects 👍

**Comment by AndreyDmitriev39r** [comment]
Ok cool! But I guess I am already learning this via practice.
