### ISSUE TITLE
Change class name for div class='row'

### ISSUE THREAD

**Issue by AndreyDmitriev39r** [DBenMoshe/contrast-ratio-repo#26]
Minor change, no rush at all.
Good opportunity to get liitle more practice with git workflow.
Maybe choose something little more descriptive for this one.
Possible options:
```
class="inputs-row"

class="users-colors-row"
```
Anything like that will be just fine I guess.

Affected files:
HTML - line 15. Well, obviously.
`          <div class="row">`
CSS - line 72. Need to change class selector also
`.row {`

**Comment by jdwilkin4** [comment]
I like `inputs-row`
