### ISSUE TITLE
Fix html from validator report

### ISSUE THREAD

**Issue by jdwilkin4** [DBenMoshe/contrast-ratio-repo#53]
I just ran our HTML through the validator and there are some errors that need addressing. 

Use the W3C tool here and paste the entire HTML document in there and run the report. 
Everything marked error needs fixing. 
https://validator.w3.org/#validate_by_input

**Comment by AndreyDmitriev39r** [comment]
This issue is related to #43 and #45, Some work is already done there. What is the best practice in such situations? Wait till #45 is merged? Assign @Okibe00 to this issue also? Something else?

**Comment by jdwilkin4** [comment]
I just merged it since I approved it earlier.
Anyone is free to take this
