### ISSUE TITLE
Discussion on how to best get started as a team

### ISSUE THREAD

**Issue by Kernix13** [DBenMoshe/contrast-ratio-repo#6]
You had a link showing an example. How about you add that to the README file along with any other pertinent links? Also, you can edit this repo to show a discussions tab where we can discuss issues (Insights > Community > Set up Discussions). I would also like to see some links on how to calculate contrast ratio given 2 colors. How is that done? Is there a formula for RGB, RGBS, HSL, HSLA, Hex? Is there a discord server for your account, this repo, for our soon-to-be collaboration group? I have a [discord server](https://discord.com/channels/921519448559583232/921519449255862325) if you want to use that one.

We need a place to discuss a lot of things like what days and times are best for communication, how many hours we will be putting in each week, etc. And I assume we need to build the page with HTML and CSS to see what it looks like then start on the JS. I am trying to finish my final project for my portfolio and then I want to start job-hunting again, but I'm having issues with a REACT/Tailwind hamburger menu. I need to get that Live before I can spend a lot of time n this. I hopefully will be done before the weekend is over but maybe not. And see, how this is not a good place to be discussing details like that!

**Comment by AndreyDmitriev39r** [comment]
One of the reasons why I suggested this project - I am interested in formula you mentioned. Now, when we started project, I guess research about it need to be done.

**Comment by jdwilkin4** [comment]
@Kernix13 
Here is the discord for the project
https://discord.com/invite/XYMb3mA3

Right now it has 7 members.

**Comment by jdwilkin4** [comment]
@AndreyDmitriev39r 
I think that the readme should have these basic details

- Project title and short paragraph description
- link to the deployed app
- tech stack
- main features
- possible screenshots of the app
- testing

**Comment by AndreyDmitriev39r** [comment]
@Kernix13
Suggestion:
break down this issue into 2 issues:
1. this issue will be about adding some info to README.
2. part about the discussions tab - I guess it should be a little administrative TODO.

**Comment by Kernix13** [comment]
> @Kernix13 Suggestion: break down this issue into 2 issues:
> 
> 2. part about the discussions tab - I guess it should be a little administrative TODO.

The Discord server should be fine but you could activate the discussion tab for this repo as well.

**Comment by jdwilkin4** [comment]
I am going to go ahead and close this issue since the discussion has moved over to the discord channel 👍
