### ISSUE TITLE
Add borders for swatches

### ISSUE THREAD

**Issue by AndreyDmitriev39r** [DBenMoshe/contrast-ratio-repo#60]
Let's add border properties for our color swatches.

When playing around #44, I noticed, that when user's colors are similar to our background-color(close to white I mean), it it super confusing.
So let's add some borders to swatches to divide it from background.

Optional
You can also consider to add some box-shadowing I guess.
https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow
Though such styling may add even more confusion. At least play around with it when working on this issue.

**Comment by Okibe00** [comment]
After trying a couple colors, seems using box shadows is the best approach to use when the colors are similar to the background.
![box shadow example](https://user-images.githubusercontent.com/78906040/184303643-8b2cd6ae-1d59-40cc-9b4c-0e14aff817af.png)
closes #60

**Comment by AndreyDmitriev39r** [comment]
This looks nice!
Maybe we don't need borders at all then - for me it's fine.

btw I am not sure why you added `closes #60` here
I thought we are using it for PRs

**Comment by Okibe00** [comment]
>btw I am not sure why you added closes #60 here
I thought we are using it for PRs
it  was a  mistake.
