### ISSUE TITLE
refactoring the results structure to include the missing AA+ and AAA+ text

### ISSUE THREAD

**Issue by Kernix13** [DBenMoshe/contrast-ratio-repo#65]
I was just looking at the spacing between elements and I wanted to reduce and increase the spacing in various spots for the main section. But then I realized we were missing the AA+ and AAA+ text. So I figured I'd just make that simple fix first. But there are some issues:

1. I noticed the classes of "pass" and "fail" are hard-coded. I assume this is known and will be controlled dynamically, but we need to finalize the HTML structure before making CSS changes.
2. The CSS and HTML will have to change a good bit to place AA+ and AAA+ over each appropriate pass/fail circle, unless we don't want to add that text. We're going to need to add a container around each p tag (small text, large text), the new text of AA+ and AAA+, and the SVG tags. Then we will have to create another flex container set to `flex-direction: column`, which means altering `.check-result`.

**Comment by Kernix13** [comment]
AA+ over the first Small text circle, AAA+ over 2nd, repeat for LArge text, and AA+ over Graphics if we are going to use that. And they need to be in their own containers so they stack in columns on small devices. After that, I would want to look at the large padding-bottom for the H1, and to tweak other areas. I don't think we head "headings". Small text and Large text are in essence the headings. It's more like a label, but a p for all should be fine.

**Comment by AndreyDmitriev39r** [comment]
>and AA+ over Graphics if we are going to use that

We kinda have #46, work in progress

>I don't think we head "headings"

From #63 discussion I think we need them... for screen readers

**Comment by Kernix13** [comment]
I saw that about the heading tags for a lot of things. I would never use a heading tag for things that are not a heading but what do I know. I'll go ahead and tinker with the HTML and CSS to see if I can add the text over each circle.

**Comment by Kernix13** [comment]
Did someone make a change to the CSS for this section? Because now the results are flex-direction: column for the 3 sets of circles?

**Comment by Kernix13** [comment]
I'm going to push my branch `fix/flex-containers` where I added some div tags and CSS for the addition of the text AA+ and AAA+. I would like to see if someone else sees the results fields on a row like I saw yesterday.

**Comment by AndreyDmitriev39r** [comment]
@Kernix13 

> Did someone make a change to the CSS for this section? Because now the results are flex-direction: column for the 3 sets of circles?

Well, that's not me - I can tell that much.

For this type of questions we have commit history:
https://github.com/DBenMoshe/contrast-ratio-repo/commits/main

**Comment by jdwilkin4** [comment]
Don't worry about headings right now.
There is a separate ticket for that #69

**Comment by jdwilkin4** [comment]
@Kernix13 
Is the end goal this? Or something similar to this? 
<img width="731" alt="Screen Shot 2022-08-13 at 12 12 03 PM" src="https://user-images.githubusercontent.com/67210629/184507594-2ec088ec-c5b6-458c-b7e6-4b7205214078.png">

If so, please update your original post to include this screenshot so everyone is on the same page for what the end result should be. 
Thanks 👍

**Comment by Kernix13** [comment]
Not exactly. Under Small text you need AA+ and AAA+, then the same for Large text. But that's the general idea. Here is a screen-shot of my branch on a large screen

![image](https://user-images.githubusercontent.com/66497948/184508381-b9d15c2c-ddee-4eda-9654-c358addd8dc7.png)

Something is wrong with my code. I think it would be best to close this issue and delete my PR. Or else I could try to reset my code somehow.

**Comment by jdwilkin4** [comment]
I have added the discussion label since this more of a design change now.

I think the next course of action is to create a mockup of what the final result is supposed to look like for larger devices and smaller devices.

You can use figma, adobe, canva, or whatever you feel comfortable with.
But it will help everyone on the team to see what the final result will look like so we can effectively review your code. 

This also mimics what would happen on the job.
Usually a new issue would be created with a figma mockup, so the developer working on this issue can take that mockup and make whatever HTML and CSS changes necessary to achieve that final result.

 > Something is wrong with my code. I think it would be best to close this issue and delete my PR. Or else I could try to reset my code somehow.

If you want to close your issue, that is fine.
If you want to keep it open, and go back a previous commit to the original css that is fine too.

**Comment by Kernix13** [comment]
Yeah, closing the issue sounds best. What about the PR for the branch on this subject?

**Comment by jdwilkin4** [comment]
For the PR, you can close that too.

**Comment by Kernix13** [comment]
Got it.

**Comment by Kernix13** [comment]
Closed the PR but it has a message of:

> Closed with unmerged commits

Is that a problem?

**Comment by jdwilkin4** [comment]
That doesn't matter since you will be deleting that branch anyway

**Comment by Kernix13** [comment]
Ok, the PR is closed and my local copy of the branch is deleted. Do I need the branch here on GitHub?

**Comment by AndreyDmitriev39r** [comment]
This branch is not needed, since it closed. It's better to delete branches, which are merged or closed
