### ISSUE TITLE
Add meta description tag in HTML file

### ISSUE THREAD

**Issue by AndreyDmitriev39r** [DBenMoshe/contrast-ratio-repo#8]
I have no idea how good description tag should look like, it's about SEO I guess.
Maybe it's just need to be descriptive(big surprise).

For those who doesn't know/doesn't remember.

This meta tag goes into head element, inside HTML file.

I wiil leave generic example here:
`<meta name="description" content="I am very descriptive description. I am supposed to be a little bit more verbose, than title">`

**Comment by Kernix13** [comment]
It should be 120-160 characters with a focus on the keyword phrase, but I question how important it is. I wrote meta descriptions for over 150 blog posts thinking it was important. And then I created a Guitar Chord Namer page for one of my websites. It's one of my portfolio items, but I did not even bother adding a meta description. When I went to check on Google the other websites that have a similar tool, I noticed my page was ranking 13 after a week or so. Then I added the meta description and then it disappeared - I could not find it.

**Comment by AndreyDmitriev39r** [comment]
Ok, good point. So description should be either good or... we should move on without description.
I will leave this issue here for now, but I will add the discussion label, let's see what others have to say.

**Comment by jdwilkin4** [comment]
I think this is a situation where it doesn't hurt to have it. 
If left out, it is not the end of the world and the project will be just fine. 
But this would make for a good, first issue though for someone new to git and the whole workflow process. 
So I vote to keep the issue 👍

**Comment by DBenMoshe** [comment]
Just made a PR addressing this issue

**Comment by AndreyDmitriev39r** [comment]
Do you want Jessica to review it? Since I am here, I can do it also I guess.
